name: Bug report
description: Report a reproducible problem in Control Center
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Include exact steps and expected vs actual behavior
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS / Environment
      placeholder: e.g., Windows 11 23H2
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      render: shell
